"""update post model for blog publishing

Revision ID: 325fe49d57c7
Revises: 89806ec9452c
Create Date: 2025-12-06 16:25:08.391423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325fe49d57c7'
down_revision = '89806ec9452c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_post_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_slug'))
        batch_op.drop_index(batch_op.f('ix_post_published'))
        batch_op.alter_column('body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('published')
        batch_op.drop_column('summary')
        batch_op.drop_column('slug')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
