"""followers

Revision ID: 89806ec9452c
Revises: 78ab8cbdcea0
Create Date: 2025-12-02 11:22:08.278805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89806ec9452c'
down_revision = '78ab8cbdcea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
